/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void randomQuoteTest(){
        Gson gson = new Gson();
        File input = new File("app/src/main/resources/recentquotes.json");
        try {
            Reader reader = new FileReader(input);
            Quotes []quotes = gson.fromJson(reader, Quotes[].class);
            assertTrue(Arrays.asList(quotes).contains("{author='Cassandra Clare', text=' “There is no pretending, Jace said with absolute clarity. I love you, and I will love you until I die, and if there is life after that, I'll love you then.�? '}"));
            assertFalse(Arrays.asList(quotes).contains("author='Bayan Hmaidy'"));
//            String actual = String.valueOf(quotes[0]);
//            System.out.println(quotes[16].toString());
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
