package quotes;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package app.src.main.java.quotes;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.Reader;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }



    public static void main(String[] args) {
        
        Gson gson = new Gson();
        File input = new File("app/src/main/resources/recentquotes.json");
        try {
            Reader reader = new FileReader(input);
            Quotes []quotes = gson.fromJson(reader, Quotes[].class);
            int min = 0;
            int max = 142;
            int random_int = (int)Math.floor(Math.random()*(max-min)+min);
            System.out.println(quotes[random_int]);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
    }
}
